// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsaHQ4C3zp2V1rp5rDsTKjcby32C0wbhE',
    appId: '1:616085272505:web:55ea4e9ed8da0ed4a7e868',
    messagingSenderId: '616085272505',
    projectId: 'todoapp-2026-366a6',
    authDomain: 'todoapp-2026-366a6.firebaseapp.com',
    storageBucket: 'todoapp-2026-366a6.firebasestorage.app',
    measurementId: 'G-930FPG3FJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSGJNQFQ3KSft8qP5QfqocGtVOlCsXyas',
    appId: '1:616085272505:android:15e1c23353ed4db4a7e868',
    messagingSenderId: '616085272505',
    projectId: 'todoapp-2026-366a6',
    storageBucket: 'todoapp-2026-366a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk6RnlCfy_qlUbRq_LbTsN1aoppvvLeuU',
    appId: '1:616085272505:ios:b7680bbdeb87e621a7e868',
    messagingSenderId: '616085272505',
    projectId: 'todoapp-2026-366a6',
    storageBucket: 'todoapp-2026-366a6.firebasestorage.app',
    iosBundleId: 'com.example.verygoodcore.todo-list-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk6RnlCfy_qlUbRq_LbTsN1aoppvvLeuU',
    appId: '1:616085272505:ios:4bf789f29e3170eca7e868',
    messagingSenderId: '616085272505',
    projectId: 'todoapp-2026-366a6',
    storageBucket: 'todoapp-2026-366a6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsaHQ4C3zp2V1rp5rDsTKjcby32C0wbhE',
    appId: '1:616085272505:web:b59fc8e8d77af811a7e868',
    messagingSenderId: '616085272505',
    projectId: 'todoapp-2026-366a6',
    authDomain: 'todoapp-2026-366a6.firebaseapp.com',
    storageBucket: 'todoapp-2026-366a6.firebasestorage.app',
    measurementId: 'G-2GKB29NENY',
  );
}
